# Generated by Django 3.0.3 on 2020-02-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('is_media', models.BooleanField()),
                ('media_url', models.URLField(verbose_name='')),
                ('correct_ans', models.CharField(max_length=50)),
                ('quiz_id', models.IntegerField()),
            ],
        ),
    ]
