# Generated by Django 3.0.3 on 2020-02-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_ans',
        ),
    ]
