# Generated by Django 3.0.3 on 2020-02-25 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200225_0936'),
        ('questions', '0002_remove_question_correct_ans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AddField(
            model_name='question',
            name='que_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Quiz_settings',
            fields=[
                ('quiz_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quiz_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ppq', models.IntegerField()),
                ('tpq', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.admin')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Quiz_settings'),
        ),
    ]
