# Generated by Django 3.0.3 on 2020-02-25 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20200225_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('option_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=200)),
                ('is_true', models.BooleanField()),
                ('que_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
            ],
        ),
    ]
