# Generated by Django 3.0.3 on 2020-03-02 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_settings',
            name='quiz_id',
        ),
        migrations.AddField(
            model_name='quiz_settings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
