# Generated by Django 3.0.3 on 2020-02-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='id',
        ),
        migrations.AlterField(
            model_name='admin',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
